Yammerkeyのサイト Ver.20240711-1
MutsumeWebDev/training1 pull request #8
Opened 2024-07-11 03:34 UTC by sejsokdjfpsakd

仮完成です。

2024-07-12 03:11 UTC, oYAs-me requested changes
おおむねの方針としては問題ないと思います．ただ改善してほしい点がいくつかあって
- [x] headのfaviconをコメントアウトしなくていいこと
- [ ] もう少しdivを使ってグルーピングしてほしい（概要配下のdivの中にh3配下のdivを入れるみたいな感じ．h3のところは同じclass名にするとかCSSの再利用がしやすいように）まあ思想あってのこれならリアクションしてくれ
- [ ] もうちょっとモダンなカラーリングにしてほしい，初心者が見て「（比較的簡単に）こんなにできるんだ！」って味わってもらいたいので，[ピュレグミのサイト](https://kanro.jp/pages/pure)みたいな色使いだといいかも
おおむねこんな感じです，あと遅くなってごめん

2024-07-12 04:10 UTC, sejsokdjfpsakd commented
> headのfaviconをコメントアウトしなくていい

外すのをすっかり忘れてました。何か独自のアイコンを載せられればと思い、一旦保留にした箇所です。直しておきます。
ちなみに、favicon.icoがルートディレクトリにあるときは、アイコンのアドレスを指定する必要はないです。(ファイル名･拡張子が1文字でも変わると指定が必要です。)そのため、現在のバージョンでもアイコンは正しく表示されているはずです。

> もう少しdivを使ってグルーピングしてほしい

それも忘れてました。言われてみればほとんど使っていませんでしたね。自分は結構使うので、自分でも驚きです。
(個人的な意見ですが)実際、Wordで簡単に書けるレベルのデザインだと`div`はほぼ要らないのですよね。1箇所だけ使っている`div`も白の透過背景を入れるためだけに(やむを得ず)使っています。`div`が大活躍するのはPowerPointで作るようなデザインの時、即ちそれだけ配置が複雑になりそうな時ですかね。
そこまでやってしまって良いのであればガッツリ使っていきますが、どうしますか？(とはいえ、スマートフォン向けのサイトだとパソコン向けに比べて利用は限定されてきそうですが。)

> h3のところは同じclass名にするとかCSSの再利用がしやすいように

ここはCSSの読みやすさ(`class`,`id`の必要最小限の利用)を目的に、タグへの直接指定をやっています。先述と同じくWordで書けるレベルのデザインだと`class`,`id`、特に見出しにおいてはほぼ使わない(使う理由が見出せない)のですよね。
ただ`div`をガッツリ使っていくのであれば、おっしゃる通りCSSの再利用が必要になるので、ネーミングに困るほど使うのですが。(これの解決のために、CSSの記述で子要素の話が出てきます。)

> もうちょっとモダンなカラーリングにしてほしい

色合いがダサいのは承知しています。
ちなみに色を統一しているのは最近の流行りだから、という理由です。(良品計画のデザインが流行っているのも、そこに起因する面は大きいと思います。)最近作られたWebサイトはあまり多くの色を使っていない(使っていても近似色である)のは、意識していなくても経験的に分かるかと思います。
とはいえ、先述した通りダサいのは事実なので、もう少し改良してみます。

> 初心者が見て「（比較的簡単に）こんなにできるんだ！」って味わってもらいたい

そうですね。そう思っていただけるよう、頑張ります

---------

よろしくお願いします！

2024-07-13 02:46 UTC, oYAs-me commented
で，レビューをして，変更を加えてもう一度プルリクエスト投げてもらうことになります
favconの部分とdivの部分についてお願いしますね

それとなんですが，スマートフォン用のサイトという想定はしていないので，まず始めはパソコン表示用のサイトの気持ちでやってもらいたいですね．
ページの制作が終わったら，発展的にスマートフォン用のCSSをつくる（レスポンシブ対応する）って感じでいいんじゃないですかね

2024-07-13 14:44 UTC, sejsokdjfpsakd commented
@oYAs-me さん
　了解です。
　今回のデザインの意図をお伝えしていませんでしたが、むつめ祭のサイトが主にスマートフォン向けになると伺っていたことから、縦長の画面でも見やすいように1列複数行を意識したものにしています。
　そういった理由から現在のデザインは、スマートフォンで見ることを主にした上でパソコン表示対応させたサイトとなっており、前後関係が変わるとかなりレイアウトは変わるかもしれません。さらに前後関係を変えると、スマートフォンサイト用CSSを作るのは高難易度になりますね。下手するとJavascriptのお世話になるかもしれません。とりあえず難しくなりすぎない程度にやってみます。

2024-07-13 14:45 UTC, oYAs-me commented
ありがとう、とりあえずなんとなくでもいいから作ってもらえるといいね

2024-07-17 16:25 UTC, closed without merging